// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6xCmej7JD8fn87TGIsPsI6qN-BobbD0I',
    appId: '1:700315889615:web:6e4212467c5667651f2cba',
    messagingSenderId: '700315889615',
    projectId: 'authbio-f0fdf',
    authDomain: 'authbio-f0fdf.firebaseapp.com',
    storageBucket: 'authbio-f0fdf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9376lOrOxl2Tmc2Ku4-XpWGee8B3PKg',
    appId: '1:700315889615:android:9a0f72c3c21050311f2cba',
    messagingSenderId: '700315889615',
    projectId: 'authbio-f0fdf',
    storageBucket: 'authbio-f0fdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgGTl0ZOTZX9hgT9TshOiW9VCWN8CxDQ',
    appId: '1:700315889615:ios:68010721896e3d6b1f2cba',
    messagingSenderId: '700315889615',
    projectId: 'authbio-f0fdf',
    storageBucket: 'authbio-f0fdf.firebasestorage.app',
    iosBundleId: 'com.example.authBio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNgGTl0ZOTZX9hgT9TshOiW9VCWN8CxDQ',
    appId: '1:700315889615:ios:68010721896e3d6b1f2cba',
    messagingSenderId: '700315889615',
    projectId: 'authbio-f0fdf',
    storageBucket: 'authbio-f0fdf.firebasestorage.app',
    iosBundleId: 'com.example.authBio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6xCmej7JD8fn87TGIsPsI6qN-BobbD0I',
    appId: '1:700315889615:web:f5817a49d1749dae1f2cba',
    messagingSenderId: '700315889615',
    projectId: 'authbio-f0fdf',
    authDomain: 'authbio-f0fdf.firebaseapp.com',
    storageBucket: 'authbio-f0fdf.firebasestorage.app',
  );
}
